### ISSUE TITLE
Add citation to your Bioinformatics paper

### ISSUE THREAD

**Issue by carden24** [KoslickiLab/fmh-funprofiler#10]
Hi, 
Thanks for the tool. I saw that you have published it already. I think I should be useful to add the citation to the tool

Hera MR, Liu S, Wei W, Rodriguez JS, Ma C, Koslicki D. Metagenomic functional profiling: to sketch or not to sketch? Bioinformatics. 2024 Sep 1;40(Suppl 2):ii165-ii173. doi: 10.1093/bioinformatics/btae397. PMID: 39230701; PMCID: PMC11373326.

**Comment by mahmudhera** [comment]
Added by commit 6fe9e0f
