### ISSUE TITLE
Add txt file containing Zenodo links for ease of wget/curl access

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/fmh-funprofiler#2]

**Comment by ShaopengLiu1** [comment]
will wait for more sketches (with multiple scale factor) and upload a full ref file. To be update soon

**Comment by ShaopengLiu1** [comment]
added scale 10,50,100,150,200,250,500 for k 7,11,15. It's a Zenodo link though:
https://github.com/KoslickiLab/fmh-funprofiler?tab=readme-ov-file#more-pre-built-sketches-with-different-scaling-factors

You may download all by just one wget of the repo like:
`wget https://zenodo.org/api/records/10981414/files-archive`

or individual files based on the corresponding links. So will save the text file for simplicity of the repo @dkoslicki
