### ISSUE TITLE
Add script to convert functional profile into a standardized output

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/fmh-funprofiler#3]
Say, something like a *.profile file (same kinda idea as a taxonomic profile), or a BIOM file or the like

**Comment by ShaopengLiu1** [comment]
Added biom transfer in Quick start
https://github.com/KoslickiLab/fmh-funprofiler?tab=readme-ov-file#quick-start

While we have no metadata nor taxonomy data involved, the biom header is almost empty so it's a simple transition.
