### ISSUE TITLE
More information on the KO Abundance

### ISSUE THREAD

**Issue by doy-pin** [KoslickiLab/fmh-funprofiler#8]
Hi,

Can you confirm if the values are relative abundance and is there a way to convert them into copies per million?

**Comment by mahmudhera** [comment]
Yes, the values are relative abundances, they should sum to 1.0.

I do not think there is any direct way to convert the values into a gross copy number. Doing so requires us to be able to definitively say that a KO is present x number of times, whereas, in the metagenome data, pieces of the genes in the KOs are present in a scattered (and perhaps messy) manner.
