### ISSUE TITLE
Paired sequencing files

### ISSUE THREAD

**Issue by annasoli** [KoslickiLab/fmh-funprofiler#9]
Hi,

Maybe this a naive question but funcprofiler handles paired fastq files?

Thanks,
Ana

**Comment by mahmudhera** [comment]
Hello, the current implementation is designed to process a single fastq file. For paired files, if you concatenate them and pass them as input, it should work just fine. 

A related side: the current implementation will not consider that reads are paired. It will just blindly extract all k-mers out of them, and use the k-mers. Hope this helps.
